# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9976db355a446e6a4cd74966adccd9128a2776110ba7a38c39290e560619b95cab5cf799152a4975e8f5f29274f1f7080a27a8fdb84cb5c5c24ad9c4d22912a4

test:
  secret_key_base: 1fe60175fa154370c46d21b7e3610357f5e0deeae1d0bb5e307c688fec2b1c6e0d2bfab27d1762482ed06677eb8048810bbcc4d258a0372b56fe06e7a8e0a32a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
